In [1]:
import pandas as pd

# membaca file csv
df = pd.read_csv("../data_cic/LDAP.csv", low_memory=False)

In [2]:
# melihat 5 data teratas
df.head()

,Unnamed: 0,Flow ID,Source IP,Source Port,Destination IP,Destination Port,Protocol,Timestamp,Flow Duration,Total Fwd Packets,...,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,SimillarHTTP,Inbound,Label
0,13605,172.16.0.5-192.168.50.4-870-2908-17,172.16.0.5,870,192.168.50.4,2908,17,2018-11-03 10:09:00.565557,1,2,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,1,NetBIOS
1,62631,172.16.0.5-192.168.50.4-871-53796-17,172.16.0.5,871,192.168.50.4,53796,17,2018-11-03 10:09:00.565559,48,2,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,1,NetBIOS
2,143869,172.16.0.5-192.168.50.4-648-40660-17,172.16.0.5,648,192.168.50.4,40660,17,2018-11-03 10:09:00.565608,1,2,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,1,NetBIOS
3,16171,172.16.0.5-192.168.50.4-872-54308-17,172.16.0.5,872,192.168.50.4,54308,17,2018-11-03 10:09:00.565993,1,2,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,1,NetBIOS
4,80845,172.16.0.5-192.168.50.4-873-40653-17,172.16.0.5,873,192.168.50.4,40653,17,2018-11-03 10:09:00.565994,1,2,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,1,NetBIOS

In [3]:
df.shape

(2113234, 88)

In [4]:
X = df.drop(columns=[' Label'])
y = df[' Label']

In [5]:
import numpy as np

X_numeric = X.select_dtypes(include=[np.number])

print("Jumlah fitur numerik:", X_numeric.shape[1])

Jumlah fitur numerik: 82

In [6]:
y_encoded = (
    y.replace({
        'BENIGN': 0,
        'LDAP': 1,
        'NetBIOS': 1
    })
    .infer_objects(copy=False)
    .astype(int)
)

print(y_encoded.value_counts())

 Label
1    2108110
0       5124
Name: count, dtype: int64

C:\Users\Lenovo\AppData\Local\Temp\ipykernel_4880\3200053040.py:2: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  y.replace({

In [7]:
print(X_numeric.dtypes.unique())
print(y_encoded.dtype)

[dtype('int64') dtype('float64')]
int64

In [8]:
import numpy as np
from sklearn.impute import SimpleImputer

# ganti inf ke NaN dulu
X_numeric.replace([np.inf, -np.inf], np.nan, inplace=True)

imputer = SimpleImputer(strategy='median')
X_imputed = imputer.fit_transform(X_numeric)

In [9]:
import pandas as pd

# hasil imputasi (array → DataFrame)
X_imputed_df = pd.DataFrame(
    X_imputed,
    columns=X_numeric.columns
)

In [10]:
print(y_encoded.head())

0    1
1    1
2    1
3    1
4    1
Name:  Label, dtype: int64

In [11]:
X_imputed_df.head()

,Unnamed: 0,Source Port,Destination Port,Protocol,Flow Duration,Total Fwd Packets,Total Backward Packets,Total Length of Fwd Packets,Total Length of Bwd Packets,Fwd Packet Length Max,...,min_seg_size_forward,Active Mean,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,Inbound
0,13605.0,870.0,2908.0,17.0,1.0,2.0,0.0,422.0,0.0,211.0,...,-1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
1,62631.0,871.0,53796.0,17.0,48.0,2.0,0.0,530.0,0.0,265.0,...,-1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
2,143869.0,648.0,40660.0,17.0,1.0,2.0,0.0,458.0,0.0,229.0,...,-1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
3,16171.0,872.0,54308.0,17.0,1.0,2.0,0.0,458.0,0.0,229.0,...,-1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
4,80845.0,873.0,40653.0,17.0,1.0,2.0,0.0,458.0,0.0,229.0,...,-1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0

In [12]:
X_imputed_df = X_imputed_df.drop(columns=[' Source Port', ' Destination Port'])

In [13]:
X_imputed_df.head()

,Unnamed: 0,Protocol,Flow Duration,Total Fwd Packets,Total Backward Packets,Total Length of Fwd Packets,Total Length of Bwd Packets,Fwd Packet Length Max,Fwd Packet Length Min,Fwd Packet Length Mean,...,min_seg_size_forward,Active Mean,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,Inbound
0,13605.0,17.0,1.0,2.0,0.0,422.0,0.0,211.0,211.0,211.0,...,-1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
1,62631.0,17.0,48.0,2.0,0.0,530.0,0.0,265.0,265.0,265.0,...,-1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
2,143869.0,17.0,1.0,2.0,0.0,458.0,0.0,229.0,229.0,229.0,...,-1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
3,16171.0,17.0,1.0,2.0,0.0,458.0,0.0,229.0,229.0,229.0,...,-1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
4,80845.0,17.0,1.0,2.0,0.0,458.0,0.0,229.0,229.0,229.0,...,-1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0

In [14]:
X_imputed_df.to_csv(
    "CICDDoS2019_LDAP_X.csv",
    index=False
)

In [15]:
y_encoded.to_csv(
    "CICDDoS2019_LDAP_y.csv",
    index=False
)

In [16]:
X_imputed_df.isna().sum().sum()

np.int64(0)